### ISSUE TITLE
センサの値を平均して取得する

### ISSUE THREAD

**Issue by satokitakata** [Sereno-Anan/SerenoDevice#15]
## 概要
センサの値を一定数取得し、その平均値を用いて雨が降っているか降っていないかを判断する。

## 具体的にやること

- [ ]センサの値を一定数取得し、その平均値と閾値を比べ雨が降っているかどうかを判別する。

## ゴール・目的（完成物の定義）
センサの値を平均して取得し、より正確に雨が降っているかどうかが判別できる。

**Comment by nemuki** [comment]
- [ ] センサの値を一定数取得し、その平均値と閾値を比べ雨が降っているかどうかを判別する。

`- [ ]` はチェックボックスになります

具体的にやることは何を使ってどうする的なことが欲しいかな
